## The basics

- ndarra.ndim
- ndarray.shape (nrows, mcolumns)
- ndarray.size
- ndarray.dtype
- ndarray.itemsize

In [1]:
import numpy as np
import matplotlib.pyplot as plt
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Array Creation

In [15]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [18]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [20]:
# The type of the array can also be explicitly specified at creation time:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
# The function zeros creates an array full of zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
# the function ones creates an array full of ones
np.ones((2, 3, 4), dtype=np.int16)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [32]:
#  the function empty creates an array whose initial content is random
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [33]:
# NumPy provides the arange function
np.arange(10, 30, 5)


array([10, 15, 20, 25])

In [34]:
# it is usually better to use the function linspac
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
from numpy import pi
x = np.linspace(0, 10 * pi, 100)
f = np.sin(x)
plt.scatter(x=x, y=f, alpha=0.5)


### Basic Operation

In [2]:
a = np.ones((2, 3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
b = rg.random((2, 3))

### Indexing, slicing and iterating

In [3]:
np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [4]:
def f(x, y):
    return 10*x+y

In [5]:
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])